"""update Project-bd

Revision ID: 30a5551b5528
Revises: a9131d4ac0f6
Create Date: 2023-09-24 17:24:30.012236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a5551b5528'
down_revision = 'a9131d4ac0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('home', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('text', sa.String(length=256), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('text')
        batch_op.drop_column('home')
        batch_op.drop_column('street')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
